services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 29092 is for internal docker network, 9092 is for your local machine
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Optional: A UI to visualize your Kafka topics and messages
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  spark:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark
    depends_on:
      - kafka
    user: root
    environment:
      - SPARK_MODE=master
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - PYTHONPATH=/opt/shared_deps
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - ./spark_jobs:/opt/app
      - ./:/opt/shared_deps
    working_dir: /opt/app
    ports:
      - "8080:8080" # Spark Master UI
      - "15002:15002"

  producer:
      build: 
        context: ./data_generator  # Path to the folder containing your Dockerfile
      container_name: fraud_producer
      depends_on:
        - kafka
      environment:
        - PYTHONPATH=/opt/shared_deps
      volumes:
        - ./data_generator/:/opt/project
        - ./:/opt/shared_deps